<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Video_widget2</name>
   <tag></tag>
   <elementGuidId>fe51bef7-71bc-4f29-ada6-c7d476617263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='widget2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#widget2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;PART 1\: PATTERNS AND NUMBERS IN NATURE AND THE WORLD \|\| MATHEMATICS IN THE MODERN WORLD&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5d10c8ee-5f36-414a-9d23-f12c86f7bcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e044fef7-90e0-4839-af3c-8186b5b8e65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share</value>
      <webElementGuid>8bd62598-9a70-4139-8e7c-bceeeb842adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PART 1: PATTERNS AND NUMBERS IN NATURE AND THE WORLD || MATHEMATICS IN THE MODERN WORLD</value>
      <webElementGuid>3bc13d8f-8147-4848-aec4-0bbefe25e051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>ae7e2a43-9250-4638-994f-715f9f31a570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>7f62978f-8f44-4955-9aaa-fbff14daf3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/J7An1mcFHBU?autoplay=1&amp;enablejsapi=1&amp;origin=http%3A%2F%2Flocalhost%3A4200&amp;widgetid=1</value>
      <webElementGuid>83c16adc-7c07-4dd7-a442-3d0ac91eb522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>widget2</value>
      <webElementGuid>42277c39-36f8-493c-9870-1ac864be246d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget2&quot;)</value>
      <webElementGuid>1d176467-298c-4e37-8f25-13d5956ec027</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='widget2']</value>
      <webElementGuid>eb53ac13-45b2-49ea-b520-779c2bb723d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ac18f786-c527-4f31-b512-27db165fab6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'PART 1: PATTERNS AND NUMBERS IN NATURE AND THE WORLD || MATHEMATICS IN THE MODERN WORLD' and @src = 'https://www.youtube.com/embed/J7An1mcFHBU?autoplay=1&amp;enablejsapi=1&amp;origin=http%3A%2F%2Flocalhost%3A4200&amp;widgetid=1' and @id = 'widget2']</value>
      <webElementGuid>df7ef7b9-952a-4416-bbe7-041cb4cfb2df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
