<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_1</name>
   <tag></tag>
   <elementGuidId>dfbe205d-9516-4648-b53d-8c85ccf76454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>path:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Play video&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>df4174d2-97ff-4294-b76d-55b13b510884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M 45,24 27,14 27,34</value>
      <webElementGuid>09926878-fda1-47f3-bc85-684627b54292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#fff</value>
      <webElementGuid>76c1f540-be84-45e5-bd51-4d91ff361db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-video-player[1]/div[@class=&quot;container&quot;]/youtube-player[1]/youtube-player-placeholder[@class=&quot;youtube-player-placeholder&quot;]/button[@class=&quot;youtube-player-placeholder-button&quot;]/svg[1]/path[2]</value>
      <webElementGuid>72802e1f-8e6b-421d-b7ac-cc20a10e2f12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
